In [1]:
import numpy as np

#append

a=np.array([1,2,3,4])
print(a)

x=np.append(a,99) # add element to array
print(x)

b=np.array([[1,2],[3,4]])
print(b)

c=np.append(b,100)
print(c)

[1 2 3 4]
[ 1  2  3  4 99]
[[1 2]
 [3 4]]
[  1   2   3   4 100]


In [ ]:
#insert()

c=np.array([1,2,3,4,5])
print(c)

d=np.insert(c,2,10) # insert value into array in single position
print(d)

e=np.insert(c,(0,3),12) # insert value into array in multiple positions
print(e)

[1 2 3 4 5]
[ 1  2 10  3  4  5]
[12  1  2  3 12  4  5]


In [ ]:
#delete()

d=np.delete(c,2) # delete value from array. ---> new_var=np.delete(var_name, position)
print(d)

[1 2 4 5]


In [ ]:
#where()

x=np.array([11,12,13,14,15,16,12,18])
print(x)

y=np.where(x==12) # find the position of data
print(y)

y=np.where(x==200)
print(y)

[11 12 13 14 15 16 12 18]
(array([1, 6]),)
(array([], dtype=int64),)


In [ ]:
#array_split()
x=np.array([11,12,13,14,15,16,12,18])

y=np.array_split(x,3)
print(y)

y=np.array_split(x,12)
print(y)

[array([11, 12, 13]), array([14, 15, 16]), array([12, 18])]
[array([11]), array([12]), array([13]), array([14]), array([15]), array([16]), array([12]), array([18]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
#asarray(var_name , dtype= datatype)

y=np.asarray(x,dtype=float) # used to change datatype of array
print(y)

y=np.asarray(x,dtype=complex)
print(y)


[11. 12. 13. 14. 15. 16. 12. 18.]
[11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 12.+0.j 18.+0.j]


In [ ]:
#unique()

t=np.array([1,2,3,4,5,6,2,3,7,5,8,90,8])
print(t)

y=np.unique(t) # Unique elements
print(y)

y=np.unique(t,return_index=True) # unique elements with position
print(y)

y=np.unique(t,return_index=True,return_counts=True) # unique elements with position and count
print(y)

[ 1  2  3  4  5  6  2  3  7  5  8 90  8]
[ 1  2  3  4  5  6  7  8 90]
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 90]), array([ 0,  1,  2,  3,  4,  5,  8, 10, 11]))
(array([ 1,  2,  3,  4,  5,  6,  7,  8, 90]), array([ 0,  1,  2,  3,  4,  5,  8, 10, 11]), array([1, 2, 2, 1, 2, 1, 1, 2, 1]))


In [ ]:
# functions in array
# 1. zeros() only zeros decimal
# 2. ones() only ones decimal
# 3. full()
# 4. eye() diagonal matrix (identity)

In [ ]:
#zeros()

x=np.zeros(3)
print(x)

x=np.zeros((2,3))
print(x)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones()

x=np.ones(5)
print(x)

x=np.ones((3,3))
print(x)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#eye()

x=np.eye(3) # Output is always 2D matrix
print(x)
print(x.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2


In [ ]:
#eye()

x=np.full((3,3),10)
print(x)

x=np.full((2,3),'a')
print(x)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[['a' 'a' 'a']
 ['a' 'a' 'a']]


In [7]:
#copy()
import numpy as np

x=np.array([11,14,15,99,100])

y=x.copy() # Both variable id address will be different
print(x)

#indexing --->
print(x[1])   #14

#var_name[position]=value
x[1]=1111
print(x)
print(y)

# print(id(x))

# print(y)
# print(id(y))

[ 11  14  15  99 100]
14
[  11 1111   15   99  100]
[ 11  14  15  99 100]


In [11]:
#view()

x=np.array([11,14,15,99,100])

y=x.view() # Modification in one also affect the another
x[1]=111
print(x)
print(y)

y[3]=2000
print(y)
print(x)

[ 11 111  15  99 100]
[ 11 111  15  99 100]
[  11  111   15 2000  100]
[  11  111   15 2000  100]


In [16]:
#split()
x=np.array([1,2,3,4,5,6,7,8])
print(x)

y=np.array_split(x,4)
print(y)

y1=np.split(x,4) # equal separation of the array is needed
print(y1)


#y1=np.split(x,3) # Error cannot divide in equal elements in array
#print(y1)

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [19]:
#add two arrays
#concatenate()
x=np.array([11,56,778,99])
y=np.array([22,55,77,44])

z=np.concatenate((x,y))
print(z)

[ 11  56 778  99  22  55  77  44]


In [24]:
#stack()

z1=np.stack((x,y)) # Convert in 2D dimensional array
print(z1)

z1=np.stack((x,y),axis=0) # Arrange as Row
print(z1)

z1=np.stack((x,y),axis=1) # Arrange as Columns
print(z1)

[[ 11  56 778  99]
 [ 22  55  77  44]]
[[ 11  56 778  99]
 [ 22  55  77  44]]
[[ 11  22]
 [ 56  55]
 [778  77]
 [ 99  44]]


In [26]:
#hstack()

z2=np.hstack((x,y)) # Convert into rows format
print(z2)

[ 11  56 778  99  22  55  77  44]


In [27]:
#vstack()

z2=np.vstack((x,y)) # Convert into column format
print(z2)

[[ 11  56 778  99]
 [ 22  55  77  44]]


In [33]:
#dstack()

z2=np.dstack((x,y)) # Convert into Height Format
print(z2)

#Convert to 3D dimensional
print(z2.ndim)

[[[ 11  22]
  [ 56  55]
  [778  77]
  [ 99  44]]]
3


In [36]:
#Arithmetic Operatipns in Numpy arrays

# a+b ----> add()

x=np.array([1,2,3])
y=np.array([1,2,3])

z=np.add(x,y)
print(z)

[2 4 6]


In [37]:
# a-b ----> subtract()

z=np.subtract(x,y)
print(z)

[0 0 0]


In [38]:
# a*b ----> multiply()

z=np.multiply(x,y)
print(z)

[1 4 9]


In [39]:
# a/b ----> divide()

z=np.divide(x,y)
print(z)

[1. 1. 1.]


In [40]:
# a%b ----> mod()

z=np.mod(x,y)
print(z)

[0 0 0]


In [42]:
# a**2 ----> power()

z=np.power(x,y)
print(z)

[ 1  4 27]


In [46]:
# Scalar Operations

x=np.array([10,20,30,40])
print(x)

#previous_var=previous_var+number
#previous_var+=number

#x=x+5
x+=5
print(x)

#x=x-5
x-=5
print(x)

#x=x/5
x=x/5
print(x)



[10 20 30 40]
[15 25 35 45]
[10 20 30 40]
[2. 4. 6. 8.]
