In [ ]:
import numpy as np

a=np.array(100)
print(a)
print(a.ndim)

print()

100
0



In [ ]:
a1=np.array([1,2,3,4]) # one dimensional array
print(a1)
print(a1.ndim) # dimension of array

print()

[1 2 3 4]
1



In [ ]:
a2=np.array([[1,2,3]]) # two dimensional array
print(a2)
print(a2.ndim)

print()

[[1 2 3]]
2



In [ ]:
a3=np.array([[1,2,3],[4,5,6]]) # two dimensional array
print(a3)
print(a3.ndim)
print(a3.shape) # Count of rows and columns in tuple

print()

[[1 2 3]
 [4 5 6]]
2
(2, 3)



In [ ]:
a4=np.array([1,2,3,4,5])
print(a4)
print(a4.ndim)
print(a4.shape)
print(a4.dtype)
print(type(a4))

[1 2 3 4 5]
1
(5,)
int64
<class 'numpy.ndarray'>


In [ ]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.shape)

print()

y=x.reshape(4,2) # Change shape of the array
print(y)
print(y.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [ ]:
y=x.reshape(8,1)
print(y)
print(y.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


In [ ]:
y=x.reshape(4,1)
print(y)
print(y.shape)

ValueError: cannot reshape array of size 8 into shape (4,1)

In [ ]:
y=x.reshape(6,2)
print(y)
print(y.shape)

ValueError: cannot reshape array of size 8 into shape (6,2)

In [ ]:
x=np.arange(0,6,2)
print(x)

[0 2 4]


In [ ]:
x=np.arange(1.1,6.2,2.1) # same as range and can use decimal values a
print(x)

[1.1 3.2 5.3]


In [ ]:
s=np.linspace(1,10) # generate sequencial number in equal format  linspace(start number , end number ,number , retstep)
print(s)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
s=np.linspace(0,10,5,retstep=True)
print(s)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)


In [ ]:
x=np.random.randint(1,8,3) #random.randint(low,high,number)
print(x)

[3 1 5]


In [ ]:
x1=np.random.randn() # ranges form -1 to 1
print(x1)

0.8246948047388994


In [ ]:
x1=np.random.randn(3)
print(x1)

[-0.19963088  0.6776925   1.00894957]


In [ ]:
x2=np.random.rand()
print(x2)

0.6102995790233935


In [ ]:
x=[1,2,3,'True','False',7+8j]
y=np.random.choice(x)
print(y)

(7+8j)


In [ ]:
np.random.shuffle(x)
print(x)

[3, 'True', 2, 'False', 1, (7+8j)]


In [ ]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x)
print(x.ndim)

print()

y=x.reshape(-1) # convert multi dimensional to single dimensional
print(y)
print(y.shape)

y=x.flatten() # convert multi dimensional to single dimensional
print(y)

print()

y=x.flatten(order='C') # convert multi dimensional to single dimensional rows format
print(y)

print()

y=x.flatten(order='F') # convert multi dimensional to single dimensional columns format
print(y)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

[1 2 3 4 5 6 7 8 9]
(9,)
[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]

[1 4 7 2 5 8 3 6 9]


In [ ]:
t=np.array([1,2,3,4],ndmin=2) # ndmin change single dimension array to multiple dimension array from 1 to 32
print(t)
print(t.ndim)
print(t.shape)

[[1 2 3 4]]
2
(1, 4)
